[package]
name = "command-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file-lock = "2.1.9"
md5 = "0.7.0"

[profile.release]
opt-level = 2
codegen-units = 1
strip = true
